document/urls.py
from django.conf.urls import url
from .views import *

app_name = 'document'

urlpatterns = [
    url(r'^create/$', DocumentCreateView.as_view(success_url="/docs"), name='create'),
    url(
        regex=r'^$',
        view=DocumentListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^(?P<pk>\d+)/$',
        view=DocumentDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^(?P<pk>\d+)/edit/$',
        view=DocumentUpdateView.as_view(),
        name='edit'
    ),
    url(r'json_docs', json_docs, name='json_docs'),
]

source/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('docs/', include('document.urls', namespace='document')),
    path('select2/', include('django_select2.urls')),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.signals import user_logged_in


class Profile(AbstractUser):

    last_ip = models.GenericIPAddressField(default='', null=True, blank=True)


def update_ip(sender, user, request, **kwargs):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    user.last_ip = ip
    user.save()


user_logged_in.connect(update_ip)

document/models.py
from django.db import models
from account.models import Profile
import datetime
from django.urls import reverse
# Create your models here.


class Source(models.Model):
    sid = models.CharField(max_length=100)
    name = models.CharField(max_length=200)
    url = models.URLField()

    def __str__(self):
        return self.name


class Document(models.Model):
    title = models.CharField(unique=True, max_length=100)
    text = models.TextField(unique=True)
    url = models.URLField()
    created = models.DateTimeField(auto_now_add=True)
    source = models.ForeignKey(Source, on_delete=models.SET_NULL, null=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    edited_times = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def editable(self):
        if (self.created + datetime.timedelta(hours=1)) < datetime.datetime.now(datetime.timezone.utc):
            return False
        else:
            return True

    def get_absolute_url(self):
        return reverse('document:detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if not self.pk:
            super().save(*args, **kwargs)
        else:
            self.edited_times += 1
            super().save(*args, **kwargs)

document/forms.py
from django import forms
from .models import Document, Source
from django_select2.forms import ModelSelect2Widget


class DocumentModelForm(forms.ModelForm):

    source = forms.ModelChoiceField(
        queryset=Source.objects.all(),
        label=u"source",
        widget=ModelSelect2Widget(
            model=Source,
            search_fields=['name__icontains'],
        )
    )

    class Meta:
        model = Document
        fields = [
            'title', 'text', 'url', 'source'
        ]

account/views.py
from django.shortcuts import render

# Create your views here.

document/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from .models import Document
from .forms import DocumentModelForm
from django.urls import reverse
# from django.db.models import Q
from datetime import datetime
from django.http import JsonResponse
from .tasks import download_selected_documents_task


class DocumentCreateView(LoginRequiredMixin, CreateView):
    model = Document
    # fields = ['title', 'text', 'url', 'source']
    form_class = DocumentModelForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        return super(DocumentCreateView, self).form_valid(form)


class DocumentListView(ListView):
    model = Document

    def get_queryset(self):
        queryset = super(DocumentListView, self).get_queryset()
        text = self.request.GET.get('text')
        title = self.request.GET.get('title')
        author = self.request.GET.get('author')
        source = self.request.GET.get('source')
        create = self.request.GET.get('created')
        update = self.request.GET.get('update')
        if text:
            queryset = queryset.filter(text__icontains=text)
        if title:
            queryset = queryset.filter(title__icontains=title)
        if author:
            queryset = queryset.filter(author__username__icontains=author)
        if source:
            queryset = queryset.filter(source__name__icontains=source)
        if create:
            created = datetime.strptime(create, '%Y-%m-%d')
            queryset = queryset.filter(created__date=created)
        if update:
            updated = datetime.strptime(update, '%Y-%m-%d')
            queryset = queryset.filter(update__date=updated)
        return queryset


class DocumentDetailView(DetailView):
    model = Document


class DocumentUpdateView(UpdateView):
    model = Document
    # fields = ['title', 'text', 'url', 'source']
    form_class = DocumentModelForm

    def form_valid(self, form):
        document = Document.objects.get(pk=self.object.pk)
        if document.editable() or self.request.user.is_superuser:
            return super(DocumentUpdateView, self).form_valid(form)
        else:
            msg = 'You can edit just first hour after create'
            form.add_error(None, msg)
            return super(DocumentUpdateView, self).form_invalid(form)

    def get_success_url(self):
        return reverse('document:detail', kwargs={'pk': self.object.pk})


def json_docs(request):
    if request.GET:
        documents = Document.objects.filter(id__in=request.GET.getlist('checks')).values()
        data = list(documents)
        if request.GET.get('to_file'):
            download_selected_documents_task.delay(data)
        return JsonResponse(data, safe=False)

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Liga Zakon Test{% endblock %}</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  {% block extra_head %}{% endblock %}
  </head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
 {% block extra_scripts %}{% endblock %}
</body>
</html>

templates/document/document_detail.html
{% extends 'base.html' %}

{% block title %} {{ block.super }} {{document.title}}{% endblock %}

{% block content %}
<strong>{{document.title}}</strong>
<p>{{document.text}}</p>
<p>Creator: {{document.author}}  <br/>Source: {{document.source.name}}</p>
<br/>
<p>Created: {{document.created}}</p>

<p>Edited {{document.edited_times}} times</p>
{% if document.edited_times > 0 %}
<p>Last edit: {{document.updated}}</p>
{% endif %}
{% if document.editable and document.author == request.user %}
<p><a href="{% url 'document:edit' document.pk %}">Edit</a></p>
{% endif %}
{% endblock %}

templates/document/document_form.html
{% extends 'base.html' %}

{% block extra_head %} {{ form.media.css }}{% endblock %}

{% block title %} {{ block.super }} New document{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>
{% endblock %}


{% block extra_scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
{{ form.media.js }}
<script>
	$(document).ready(function() {
	$(".select2-container").css("width","340px");
})
</script>
{% endblock %}

templates/document/document_list.html
{% extends 'base.html' %}

{% block content %}
<div>
	<form action="" method="GET">
		   <label>Search by title</label>
	       <input type="text" name="title" />

		   
	       <label>Search by author username</label>
	       <input type="text" name="author" />

	       <label>Create date</label>
	       <input type="date" name="created"
       			value="2019-01-29"
       			min="2019-01-01" max="2019-12-31">
	       <p>
		   
	       <label>Search by text</label>
	       <input type="text" name="text" />

		   <label>Search by source name</label>
	       <input type="text" name="source" />

	       <label>Edit date</label>
	       <input type="date" name="updated"
       			value="2019-01-29"
       			min="2019-01-01" max="2019-12-31">

	       <button type="submit">search</button>
	</form>
</div>

<form action="{% url 'document:json_docs' %}" method='GET'>
	{% for doc in document_list %}
	<div>
		<input type="checkbox" name="checks" value="{{doc.id}}" />
		<a href="{{doc.get_absolute_url}}">{{doc.title}}</a>
		<p>{{doc.text}}</p>
		<p>Creator: {{doc.author}}  <br/>Source: {{doc.source.name}}</p>
	</div>
	{% endfor %}
		<label>Download file</label>
		<input type="checkbox" name="to_file" value="True" />
		<br><a href="{% url 'document:create' %}">Add new doc</a>
		<br><button type="submit">Generate json</button>
	</form>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
  <p><a href="{% url 'document:create' %}">Create new document</a></p>
  
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
<p><a href="{% url 'document:list' %}">Show all documents</a></p>

{% endblock %}